name = "tester2"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.133.223.52:2096"
UUID = "1dc1c337-dd10-422e-906b-c75cf21f1abf"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
